### ISSUE TITLE
Enhancements: filtering

### ISSUE THREAD

**Issue by TotallyInformation** [vdemedes/npm-search#11]
Hi,

Any plans to add some additional search capabilities? 

NPM is becoming a victim of its own success and the npm website does not have the filtering needed to be able to search through modules effectively.

Options for filtering on last update age, number of stars and so on would be fantastic.

**Comment by vadimdemedes** [comment]
Hey, nope, no such plans. This app was intended as a "quick find" sort of thing, rather than a full-featured npm search. I recommend npms.io for such things.
